# .github/workflows/read_secret.yml
name: Read Secret Example

on:
  push:
    branches:
      - main

jobs:
  read_secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read secret and set MY_VAR
        env:
          MY_VAR: ${{ secrets.KEY }}
        run: |
          echo "MY_VAR value is: $MY_VAR"
