# .github/workflows/read_secret.yml
name: Read Secret Example

on:
  push:
    branches:
      - main

jobs:
  read_secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Python script
        env:
          MY_VAR: ${{ secrets.KEY }}
        run: |
          echo "import os" > script.py
          echo "print('MY_VAR is:', os.getenv('MY_VAR'))" >> script.py
          python script.py
