name: Fetch License

on:
  push:
    branches:
      - main

jobs:
  fetch_license:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # 指定 Python 版本

      - name: Install requests
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run fetch license script
        env:
          LICENSE_KEY: ${{ secrets.YOUR_SECRET_KEY }}  # 从 Secrets 中获取密钥
        run: |
          python fetch_license.py
