name: Fetch License

on:
  push:
    branches:
      - main

jobs:
  fetch_license:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get License
        env:
          LICENSE_KEY: ${{ secrets.KEY }}  # 从 Secrets 中获取密钥
        run: |
          RESPONSE=$(curl -s "https://api.hostmonit.com/get_license?license=${LICENSE_KEY}")
          echo "License Response: $RESPONSE"
