# .github/workflows/fetch_license.yml
name: Fetch License

on:
  push:
    branches:
      - main

jobs:
  fetch_license:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch license using curl
        env:
          LICENSE_KEY: ${{ secrets.KEY }}
        run: |
          curl -s "https://api.hostmonit.com/get_license?license=${LICENSE_KEY}"
