# .github/workflows/read_secret.yml
name: Read Secret Example

on:
  push:
    branches:
      - main

jobs:
  read_secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make MY_VAR from secret
        env:
          MY_VAR: ${{ secrets.KEY }}
        run: |
          echo "MY_VAR is: $MY_VAR"

      - name: Debug secrets
        run: |
          echo "Secret KEY value is: ${{ secrets.KEY }}"
