# .github/workflows/save_secret_to_file.yml
name: Save Secret to File

on:
  push:
    branches:
      - main

jobs:
  save_secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Write secret to file
        run: |
          echo "${{ secrets.KEY }}" > secret.txt

      - name: Upload secret file
        uses: actions/upload-artifact@v2
        with:
          name: secret-file
          path: secret.txt
